#!/bin/bash --norc
#@(#) brown(1sh) - example of changing xterm(1) using esc(1)
xrdb -merge <<\EOF
XTerm*VT100.geometry:	80x24
EOF
esc -xrdb|xrdb -merge
esc -bg brown -fg white -rows 40 -cols 132 -cr red -fn 5
t
exit
