#!/bin/bash --norc
#@(#) brown(1sh) - example of changing xterm(1) using esc(1)
xrdb -merge <<\EOF
XTerm*VT100.geometry:	80x24
EOF
# became very very slow XTerm(353) 20221217
#esc -xrdb|xrdb -merge
esc -bg black -fg white -rows 40 -cols 132 -cr red -fn 5
t
exit
