#!/bin/sh
#!/bin/bash
#ident  "@(#)colour.sh  1.0  Change the background color of (some) terminals -  John S. Urban"
# xterm
# gnome-terminal
# mintty
#
# $0 color_name
# $0 # prompts for a selection
####################################################
GETKEY(){
printf "${*}"

#BASH#old_tty_settings=$(stty -g)   # Save settings.
old_tty_settings=`stty -g`   # Save settings.

stty -icanon
#KEY=$(head -c1)          

#BASH#KEY=$(dd bs=1 count=1 2>/dev/null)
KEY=`dd bs=1 count=1 2>/dev/null`

stty "$old_tty_settings"      # Restore settings.
}
####################################################
GETKEY(){
printf "keep $COLOR ?"
read KEY < $TTY
echo
}
####################################################


if [ "$*" != '' ]
then
   COLOR="$1"
   esc -bg "$COLOR"
   FGCOLOR="$2"
   [ "$FGCOLOR" = '' ] || esc -fg "$FGCOLOR" # set foreground
   CRCOLOR="$3"
   [ "$CRCOLOR" = '' ] || esc -cr "$CRCOLOR" # set cursor color
else
   TTY=`tty`
   showrgb |while read R G B COLOR COLOR2
   do
      [ "$COLOR2" != '' ] && continue
      esc -bg "$COLOR"
      GETKEY "keep $COLOR ?"
      case "$KEY" in
      y*|Y*) 
      break;;
      esac
   done
fi
exit
