#!/bin/bash
# must set $MANPATH to the directory to build directory for
# must set $SECTION to manpage section like 3m_color
MANPATH=${1:-$MANPATH}
SECTION=${2:-$SECTION}
DEMO_OUTDIR=${3:-$DEMO_OUTDIR}
DEMO_OUTDIR=${DEMO_OUTDIR:-../../test/demos/}
DEMO_SUBDIR=${DEMO_SUBDIR:-TRUE}
cat <<EOF
>>>> Extract demo program from manpages with 
     MANPATH=$MANPATH
     SECTION=$SECTION
     DEMO_OUTDIR=$DEMO_OUTDIR
     DEMO_SUBDIR=$DEMO_SUBDIR
EOF
cd $MANPATH/man3
man -k .|cat -n
for TOPIC in $(ls *.$SECTION*)
do
   TOPIC=$(basename $TOPIC .gz)
   echo ">>>> $TOPIC"
   SHORTNAME=$(basename $TOPIC .$SECTION)
   if [ "$DEMO_SUBDIR" = TRUE ]
   then
      mkdir -p $DEMO_OUTDIR/$SHORTNAME
      SHORTNAME_DEMO=$DEMO_OUTDIR/$SHORTNAME/demo_$SHORTNAME.f90
   else
      mkdir -p $DEMO_OUTDIR
      SHORTNAME_DEMO=$DEMO_OUTDIR/demo_$SHORTNAME.f90
   fi
   man -s $SECTION $TOPIC|
       tee -a /tmp/x-|
       col -b|
       expand|
       sed -n -e '\%^[ !]*program  *demo_%,\%^[ !]*end  *program  *demo_%{p}' > $SHORTNAME_DEMO
       if  test ! -s "$SHORTNAME_DEMO"
       then
         rm $SHORTNAME_DEMO
       fi
       if grep -q '^[#$]' $SHORTNAME_DEMO
       then
          mv $SHORTNAME_DEMO ${SHORTNAME_DEMO/.f90}.F90
       fi
done

# show all manpages
env MANWIDTH=80 man --regex '.*'|col -b
exit
