#!/bin/bash
#@(#) for .htm files assumed to be part of the github projects add HTML header and footer
# by convention they are HTML files named *.htm and when converted to text have the format of 
# a manpage. Used for generating code documentation in conjunction with prep(1) $BLOCK sections
HERE=$(dirname $0)
export PATH=$PATH:$HERE:$HERE/bash_sub
header.sh
cat $*
footer.sh
exit
