#!/bin/bash
export SYSTEMTYPE_R=Linux_ifort
export SYSTEMTYPE=Linux
export SYSTEMTYPE_R=Linux_ifort
export SYSTEMTYPE=Linux
systemtype
exec $*
exit
# install 20GB+ Intel compiler
sudo apt install intel-basekit intel-hpckit

# useful options
ifort -fp-model precise -pc64 -align all -reentrancy threaded -nogen-interfaces -assume byterecl \
 -warn all -check all -error-limit 1 -traceback -O0 -g \
 fpm_intel.F90
