#!/bin/bash
export SYSTEMTYPE_R=Linux_nvfortran
export SYSTEMTYPE=Linux
source /etc/profile.d/modules.sh
module use /opt/nvidia/hpc_sdk/modulefiles
module load nvhpc
hash -r
PATH=$HOME/bin/$SYSTEM_TYPE_R/:$PATH
$*
exit
