#!/bin/bash
#@(#) dump sqlite3 database file as CSV (Comma Separated Values)
for DATABASE_FILE in $*
do
   for TABLE in $(sqlite3 $DATABASE_FILE .table)
   do
      (
      sqlite3 -csv -header $DATABASE_FILE 'SELECT * FROM '"$TABLE;"
      )
   done
done
exit
