#!/bin/bash
# @(#) viw(1sh) - find command with which(1) and edit it
# if a tty is attached call the editor on the file, else cat(1) it to stdout
if tty -s
then
   # use the user-specified editor else vim(1)
   #EDIT=${FCEDIT:-${EDITOR:-${VISUAL:-vim -c 'set ft=man ts=8 nomod nolist nonu' -c 'nnoremap i <nop>'}}}
   EDIT=${FCEDIT:-${EDITOR:-${VISUAL:-vim}}}
   #$EDIT $(which -a $*)
   $EDIT $(fcmd $*)
else
   #cat $(which -a $*)
   cat $(fcmd $*)
fi
